-- MySQL Script generated by MySQL Workbench
-- Mon Oct 21 05:53:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quanlynhansu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quanlynhansu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quanlynhansu` DEFAULT CHARACTER SET utf8 ;
USE `quanlynhansu` ;

-- -----------------------------------------------------
-- Table `quanlynhansu`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlynhansu`.`employee` (
  `id` INT(255) NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `birthday` VARCHAR(255) NULL DEFAULT NULL,
  `gender` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `no_UNIQUE` (`no` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (1,'E01','Bui Thi Thanh Tam','01/0/1998','Nu','0344704400','thanhtambuh@gmail.com',NULL);
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (2,'E02','Tran Viet Son','19/08/1998','Nam','0932191045','01263519039son@gmail.com',NULL);
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (3,'E03','Nguyen Van Quang','','Nam','0968104244','quangboon@gmail.com',NULL);
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (4,'E04','Le Hoang',NULL,'Nam','035485515','hoangdev@gmail.com',NULL);
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (5,'E05','Nguyen Hieu',NULL,'Nam','0344704400','devhieu@gmail.com',NULL);
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (6,'E06','To Thanh Sang',NULL,'Nam','0349103131','sangto@gmail.com',NULL);
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (7,'E07','Ho Thi My Trang','21/03/1998','Nu','0968976201','trang2103@gmail.com',NULL);
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (8,'E08','Le Thi Le Huyen',NULL,'Nu','0382863630','huyen1905@gmail.com',NULL);
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (9,'E09','Nguyen Ngoc Quynh','01/01/1998','Nu','0983173339','quynhnn1010@gmail.com',NULL);
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (10,'E010','Ha Tran','19/01/1998','Nu','0983173339','hatran1905@gmail.com','STHC - Saigontourist Hospitality College');
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (31,'E011','Le Vo Dong Hoi','22/02/1998','nu','','donghoi2202@gmail.com','');
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (46,'E012','Le Van Thuan','23/3/1998','nam','0983172229','16130606@st.hcmuaf.edu.vn','Nha Trang');
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (49,'E013','Ha Vien Phung','21/12/2018','khong xac dinh','','','Lai Vung');
INSERT INTO `` (`id`,`no`,`name`,`birthday`,`gender`,`phone`,`email`,`address`) VALUES (50,'E014','Pham Duc Huy','20/10/1998','nam','0966778899','huypccc@gmail.com','Nha Trang');
